Dicrionary = {
    ru: {
        "А": {
            "Армейский блеск": "Army Sheen",
            "Анодированная синева": "Anodized Navy",
            "Апельсиновая корка": "Orange Peel",
            "Анодированный металл": "Anodized Gunmetal",
            "Азимов": "Asiimov",
            "Аид": "Hades",
            "Айзек": "Isaac",
            "Армейская сетка": "Army Mesh",
            "Антитерраса": "Counter Terrace",
            "Антиквариат": "Antique",
            "Алоха": "Aloha",
            "Астерион": "Asterion",
            "Армейский спецназ": "Army Recon",
            "Арктическая сетка": "Glacier Mesh",
            "Азарт": "High Roller"
        },
        "Б": {
            "Буря на закате 壱": "Sunset Storm 壱",
            "Буря на закате 弐": "Sunset Storm 弐",
            "Бронзовая декорация": "Bronze Deco",
            "Бамбуковые заросли": "Bamboo Forest",
            "Бизнес-класс": "Business Class",
            "Блокировка": "System Lock",
            "Бульдозер": "Bulldozer",
            "Боец": "Man-o'-war",
            "Буря": "Tempest",
            "В центре внимания": "Limelight",
            "Безмятежность": "Serenity",
            "Белое напыление": "Sage Spray",
            "Броня": "Armor Core",
            "Брифинг": "Briefing",
            "Бунт": "Riot",
            "Бамбук": "Bamboo Print"
        },
        "В": {
            "Виктория": "Victoria",
            "Возмездие": "Retribution",
            "Валентность": "Valence",
            "Возвращение":  "Re-Entry",
            "Восходящий череп": "Rising Skull",
            "Ветеран": "Fubar",
            "Времена года": "Seasons",
            "Вороненая сталь": "Blue Steel",
            "Воздушный шлюз": "Airlock",
            "Воин дорог": "Chopper",
            "Вирус": "Virus",
            "Война в пустыне": "Desert Warfare",
            "Вихрь джунглей": "Jungle Slipstream"
        },
        "Г": {
            "Гексан": "Hexane",
            "Городской щебень": "Urban Rubble",
            "Гипноз": "Hypnotic",
            "Городской шок": "Urban Shock",
            "Гемоглобин": "Hemoglobin",
            "Городская опасность": "Urban Hazard",
            "Горелка Бунзена": "Bunsen Burner",
            "Гремучая смерть": "Death Rattle",
            "Грунтовая вода": "Groundwater",
            "Градиент": "Fade",
            "Грани": "Facets",
            "Гроза": "Storm",
            "Графит": "Graphite",
            "Грецкий орех": "Walnut",
            "Горелка Теклу": "Teclu Burner",
            "Голубая хвоя": "Blue Spruce",
            "Городская перфорация": "Urban Perforated",
            "Гравировка": "Graven",
            "Горн войны": "Akoben",
            "Гран-при": "Grand Prix",
            "Груда костей": "Bone Pile",
            "Городская штриховка": "Urban Dashed"
        },
        "Д": {
            "Директива": "Directive",
            "Дракон-предводитель": "Kumicho Dragon",
            "Духовики": "Ventilators",
            "Драконий дуэт": "Dualing Dragons",
            "Дуэлист": "Duelist",
            "Дань прошлому": "Retrobution",
            "Джунгли": "Jungle",
            "Дух воды": "Water Elemental",
            "Дровосек": "Woodsman",
            "Дерн": "Turf",
            "Дух огня": "Fire Elemental",
            "Джамбия": "Jambiya",
            "Дротик": "Dart",
            "Демонтаж": "Teardown"
        },
        "Е": {
            "Едва зеленый": "Para Green"
        },
        "Ё": {
            
        },
        "Ж": {
            "Желтый жакет": "Yellow Jacket",
            "Жернов": "Grinder",
            "Железное покрытие": "Iron Clad",
            "Жар": "Heat",
            "Желто-черные полосы": "Hazard",
            "Железная роза": "Rose Iron",
            "Жнец": "Harvester"
        },
        "З": {
            "Зеленая клетка": "Green Plaid",
            "Заговор": "Conspiracy",
            "Золотой карп": "Golden Koi",
            "Захоронение": "Catacombs",
            "Защитник империи": "Imperial",
            "Зыбь": "Ripple",
            "Заражение": "Contamination",
            "Закрученный": "Torque",
            "Зеленое яблоко": "Green Apple",
            "Змеиная кожа": "Snake Camo",
            "Зигги": "Ziggy",
            "Заклятый враг": "Nemesis",
            "Закат": "Setting Sun",
            "Заблуждение": "Delusion",
            "Знак воды": "Water Sigil"
        },
        "И": {
            "Изумруд": "Emerald",
            "Императорский дракон": "Imperial Dragon",
            "Индиго": "Indigo",
            "Императрица": "The Empress",
            "Изумрудный дракон": "Emerald Dragon"
        },
        "Й": {
            "Йорик": "Yorick"
        },
        "К": {
            "Красный ястреб": "Red Astor",
            "Кровавая паутина": "Crimson Web",
            "Королевская чета": "Royal Consorts",
            "Картель": "Cartel",
            "Колония": "Colony",
            "Капилляры": "Capillary",
            "Ками": "Kami",
            "Карамельное яблоко": "Candy Apple",
            "Королевский легион": "Royal Legion",
            "Кортисейра": "Corticera",
            "Кольчуга": "Chainmail",
            "Красные фрагменты": "Red FragCam",
            "Красный камень": "Red Rock",
            "Костяная маска": "Bone Mask",
            "Красный кварц": "Red Quartz",
            "Калька": "Blueprint",
            "Кровавый тигр": "Blood Tiger",
            "Королевский синий": "Royal Blue",
            "Кайман": "Caiman",
            "Камуфляж": "Overgrowth",
            "Космический воитель": "Nebula Crusader",
            "Контрастные цвета" : "Contrast Spray",
            "Крокодиловая сетка" : "Gator Mesh",
            "Конфуз": "Dazzle",
            "Крикун": "Loudmouth",
            "Калифорнийский камуфляж": "CaliCamo",
            "Карп кои": "Koi",
            "Клетчатая сталь": "Caged Steel",
            "Кракен": "The Kraken",
            "Костемолка": "Bone Machine",
            "Красный питон": "Red Python",
            "Красная кожа": "Red Leather",
            "Клочья": "Tatter",
            "Кожа": "Leather",
            "Каркас": "Scaffold",
            "Капрал": "Corporal",
            "Карамель": "Caramel"
        },
        "Л": {
            "Листовая сталь": "Tread Plate",
            "Луна в знаке Весов": "Moon in Libra",
            "Лихач": "Hot Shot",
            "Лесная ночь": "Forest Night",
            "Литьё": "Ironwork",
            "Ласка": "Weasel",
            "Латунь": "Brass",
            "Лабиринт": "Pathfinder",
            "Луговые листья": "Grassland Leaves",
            "Ледниковый покров": "Ice Cap",
            "Лавина": "Avalanche",
            "Лесные листья": "Forest Leaves",
            "Лама-пушка": "Llama Cannon",
            "Лесничий": "Ranger",
            "Лазурный хищник": "Lapis Gator",
            "Лабиринт минотавра": "Minotaur's Labyrinth"
        },
        "М": {
            "Метеорит": "Meteorite",
            "Медная галактика": "Copper Galaxy",
            "Мраморный гранит": "Granite Marbleized",
            "Малиновое кимоно": "Crimson Kimono",
            "Мятное кимоно": "Mint Kimono",
            "Магма" : "Magma",
            "Мраморный буран" : "Blizzard Marbleized",
            "Моррис": "Morris",
            "Мозаика": "Mosaico",
            "Медь": "Copper",
            "Малахит": "Malachite",
            "Мёртвая хватка": "Death Grip",
            "Мрак": "Grim",
            "Модуль": "Module",
            "Металлические цветы": "Metal Flowers"
        },
        "Н": {
            "Нитро": "Nitro",
            "Новая фуксия": "The Fuschia Is Now",
            "Ночь": "Night",
            "Ночная буря": "Midnight Storm",
            "Нага": "Naga",
            "Наследие": "Heirloom",
            "Наемник": "Contractor",
            "Неистовый даймё": "Violent Daimyo",
            "Неоновое кимоно": "Neon Kimono",
            "Неонуар": "Neo-Noir",
            "Нержавейка": "Stainless",
            "Ночные операции": "Night Ops",
            "Насыщенная вода" : "Hard Water",
            "Неоновый гонщик": "Neon Rider",
            "Неглубокая могила" : "Shallow Grave"
        },
        "О": {
            "Отравленный дротик": "Poison Dart",
            "Оксидное пламя": "Oxide Blaze",
            "Осадок": "Mudder",
            "Обезьянье дело": "Monkey Business",
            "Океанские мотивы": "Oceanic",
            "Океанская пена": "Ocean Foam",
            "Охотник": "Wingshot",
            "Окостеневший": "Ossified",
            "Орион": "Orion",
            "Объемные шестиугольники": "Memento",
            "Оранжевое пламя": "Blaze Orange",
            "Оригами": "Origami",
            "Особая доставка": "Special Delivery",
            "Оливковая клетка": "Olive Plaid",
            "Облучение": "Exposure",
            "Океанская глубина": "Photic Zone",
            "Осирис": "Osiris"
        },
        "П": {
            "Полимер": "Polymer",
            "Поул-позиция": "Pole Position",
            "Послание коринфянам": "Corinthian",
            "Пилот": "Pilot",
            "Пищаль": "Hand Cannon",
            "Пиксельный камуфляж «Город»": "Urban DDPAT",
            "Пламя": "Blaze",
            "Пантера": "Panther",
            "Причал": "Marina",
            "Патина": "Stained",
            "Подрыв": "Demolition",
            "Птичьи игры": "Fowl Play",
            "Паслен": "Nightshade",
            "Поверхностная закалка": "Case Hardened",
            "Пришелец": "Off World",
            "Пустынный повстанец": "Wasteland Rebel",
            "Призраки": "Wraiths",
            "Песчаные дюны": "Sand Dune",
            "Пистолет": "Handgun",
            "Пульс": "Pulse",
            "Прощальный оскал": "See Ya Later",
            "Покойник": "Muertos",
            "Пиксельный камуфляж «Металлический»": "Metallic DDPAT",
            "Пятно": "Splash",
            "Пороховой дым": "Gunsmoke",
            "Песчаная буря": "Sandstorm",
            "Проводник": "Lead Conduit",
            "Подтвержденное убийство": "Kill Confirmed",
            "Перезагрузка": "Reboot",
            "Призрак": "Spectre",
            "Приморский прогноз": "Shipping Forecast",
            "Пиксельный камуфляж «Джунгли»" : "Jungle DDPAT",
            "Петроглиф": "Petroglyph",
            "Преторианец": "Praetorian",
            "Поджигатель": "Firestarter",
            "Погрузчик": "Power Loader",
            "Пустынная атака": "Desert-Strike",
            "Почва": "Terrain",
            "Пальма": "Palm",
            "Полярная сетка": "Polar Mesh",
            "Призрачный камуфляж": "Ghost Camo",
            "Принцесса пустошей": "Wasteland Princess",
            "Первый класс": "First Class",
            "Пыльник": "Rust Coat",
            "Пиксельный камуфляж «Лес»": "Forest DDPAT",
            "Полная остановка": "Full Stop",
            "Пиксельный камуфляж «Ржавчина»": "Orange DDPAT",
            "Поток": "Slipstream",
            "Последнее погружение": "Last Dive",
            "Плотоядный": "Carnivore",
            "Пассажир": "Commuter",
            "Проклятие": "Curse",
            "Перистое облако": "Cirrus",
            "Пыльный осадок": "Sand Scale",
            "Песчаная штриховка": "Sand Dashed",
            "Песчаное напыление": "Sand Spray",
            "Первобытный саблезуб": "Primal Saber"
        },
        "Р": {
            "Ржавый кобальт": "Cobalt Disruption",
            "Ржавая сталь": "Steel Disruption",
            "Роспись": "Mehndi",
            "Реактор": "Reactor",
            "Райский страж": "Heaven Guard",
            "Радиоактивная опасность": "Irradiated Alert",
            "Радиоактивные отходы": "Nuclear Waste",
            "Расцветающая ветка": "Bloomstick",
            "Разбойник": "Highwayman",
            "Ртуть": "Quicksilver",
            "Радиоактивные осадки": "Fallout Warning",
            "Рубиновый ядовитый дротик": "Ruby Poison Dart",
            "Резной приклад": "Shapewood"
        },
        "С": {
            "Сян-лю": "Xiangliu",
            "Смокинг": "Tuxedo",
            "Синий кварц": "Cobalt Quartz",
            "Скоростной зверь": "Hyper Beast",
            "Скумбрия": "Scumbria",
            "Серебряный кварц": "Silver Quartz",
            "Сумеречная галактика": "Twilight Galaxy",
            "Синяя трещина": "Blue Fissure",
            "Слоновая кость": "Ivory",
            "Серебро": "Silver",
            "Скорпион": "Scorpion",
            "Снежная мгла": "Whiteout",
            "Сверхновая": "Supernova",
            "Современный охотник": "Modern Hunter",
            "Северный лес": "Boreal Forest",
            "Смерч": "Tornado",
            "Смешанный камуфляж": "VariCamo",
            "Синий титан": "Blue Titanium",
            "Сайрекс": "Cyrex",
            "Следы асфальта": "Road Rash",
            "Сыворотка": "Serum",
            "Страж": "Guardian",
            "Судак": "Zander",
            "Спокойствие": "Tranquility",
            "Смешанный синий камуфляж": "VariCamo Blue",
            "Слизь": "Goo",
            "Смертельный яд": "Deadly Poison",
            "Сезон засухи": "Dry Season",
            "Сажа": "Scorched",
            "Слепое пятно": "Blind Spot",
            "Смертоносные кошечки": "Death by Kitty",
            "Суд Анубиса": "Judgement of Anubis",
            "Синяя струя": "Blue Streak",
            "Синие полутона": "Cobalt Halftone"
        },
        "Т": {
            "Тактикотик": "Tacticat",
            "Тигр": "Tigris",
            "Твист": "Twist",
            "Терн": "Briar",
            "Триумвират": "Triumvirate",
            "Татуировка дракона": "Dragon Tattoo",
            "Треснувший опал": "Cracked Opal",
            "Трафарет": "Cut Out",
            "Топливный инжектор": "Fuel Injector",
            "Терраса": "Terrace",
            "Токсичность": "Toxic",
            "Темная вода": "Dark Water",
            "Тра-та-та": "Bratatat",
            "Тень бамбука": "Bamboo Shadow",
            "Градиент": "Fade",
            "Темный век": "Dark Age",
            "Треугольник" : "Trigon",
            "Топливный стержень": "Fuel Rod"
        },
        "У": {
            "Удар кобры": "Cobra Strike",
            "Улей": "Hive",
            "Укус изумрудного яда": "Emerald Poison Dart",
            "Ударная дрель" : "Impact Drill",
            "Ультрафиолет": "Ultraviolet",
            "Утечка отходов": "Bioleak",
            "Углепластик": "Carbon Fiber"
        },
        "Ф": {
            "Франклин": "Franklin"
        },
        "Х": {
            "Хищник": "Predator",
            "Хроматика": "Rangeen",
            "Хот-род": "Hot Rod",
            "Хладнокровный": "Cold Blooded",
            "Химический зеленый": "Chemical Green"
        },
        "Ц": {
            "Цвет луга": "Grassland",
            "Цвета прибоя": "Undertow"
        },
        "Ч": {
            "Чаша": "Chalice",
            "Черная лимба": "Black Limba",
            "Частица титана": "Titanium Bit",
            "Чайка": "Seabird",
            "Черный галстук": "Black Tie",
            "Чертята": "Impire",
            "Черепа": "Skulls"
        },
        "Ш": {
            "Штамп": "Imprint"
        },
        "Щ": {
            
        },
        "Ъ": {
            "Flame Test": "Flame Test",
            "Moonrise": "Moonrise",
            "Urban Hazard": "Urban Hazard",
            "Cortex": "Cortex",
            "Grip": "Grip"
        },
        "Ы": {
            
        },
        "Ь": {
            
        },
        "Э": {
            "Эконом-класс": "Coach Class",
            "Эхолот": "Sonar",
            "Экзо": "Exo",
            "Элитное снаряжение": "Elite Build"
        },
        "Ю": {
            
        },
        "Я": {
            "Янтарный градиент": "Amber Fade",
            "Ядерная угроза": "Nuclear Threat",
            "Ядро кобальта": "Cobalt Core",
            "Ядозуб": "Gila",
            "Ядерный сад": "Nuclear Garden",
            "Ящик Пандоры": "Pandora's Box",
            "Ясень": "Ash Wood"
        }
    }
};